window.CHINA_POP_TEMPLATE_CONFIGS = [
  {
    id: "horseyear",
    name: "春节马年 / Spring Horse 2026",
    category: "festival",
    renderer: "horseyear",
    colors: ["#b91512", "#f2c45a", "#ff5b19"],
    copy: {
      titleZh: "春节快乐",
      titleEn: "HAPPY SPRING FESTIVAL",
      subtitleZh: "2026 马年吉祥",
      subtitleEn: "2026 YEAR OF THE HORSE",
      seal: "福",
    },
    personSlot: { x: 0.5, y: 0.42, scale: 0.78, shape: "oval" },
  },
  {
    id: "morning",
    name: "早上好 / Good Morning",
    category: "daily",
    renderer: "dailyGreeting",
    colors: ["#fa4b17", "#ffe06c", "#6fcf63"],
    copy: {
      greeting: "早上好",
      greetingEn: "GOOD MORNING",
      sub: "新的一天 鸿运当头",
      subEn: "NEW DAY, BIG LUCK",
      seal: "旺",
      time: "morning",
    },
    personSlot: { x: 0.5, y: 0.43, scale: 0.76, shape: "oval" },
  },
  {
    id: "noon",
    name: "中午好 / Good Noon",
    category: "daily",
    renderer: "dailyGreeting",
    colors: ["#e23518", "#ffd15f", "#8bd45b"],
    copy: {
      greeting: "中午好",
      greetingEn: "GOOD NOON",
      sub: "吃饱喝足 财气十足",
      subEn: "EAT WELL, GET RICH",
      seal: "饱",
      time: "noon",
    },
    personSlot: { x: 0.5, y: 0.43, scale: 0.76, shape: "oval" },
  },
  {
    id: "evening",
    name: "晚上好 / Good Evening",
    category: "daily",
    renderer: "dailyGreeting",
    colors: ["#261447", "#ff3d6e", "#ffd85a"],
    copy: {
      greeting: "晚上好",
      greetingEn: "GOOD EVENING",
      sub: "灯火辉煌 好运登场",
      subEn: "LIGHTS ON, LUCK UP",
      seal: "夜",
      time: "evening",
    },
    personSlot: { x: 0.5, y: 0.43, scale: 0.76, shape: "oval" },
  },
  {
    id: "squaredance",
    name: "广场舞 / Square Dance",
    category: "scene",
    renderer: "squareDance",
    colors: ["#d91417", "#ffe66d", "#4bd2ff"],
    copy: {
      titleZh: "广场舞天团",
      titleEn: "SQUARE DANCE CREW",
      subtitleZh: "跟上节奏 好运翻倍",
      subtitleEn: "MOVE TOGETHER, LUCK FOREVER",
      seal: "舞",
    },
    personSlot: { x: 0.5, y: 0.46, scale: 0.72, shape: "full" },
  },
  {
    id: "bellypark",
    name: "公园大爷 / Park Uncle",
    category: "scene",
    renderer: "bellyPark",
    colors: ["#4c9a52", "#f35a22", "#ffe48a"],
    copy: {
      titleZh: "公园纳凉局",
      titleEn: "PARK COOLING CLUB",
      subtitleZh: "背心卷起 才是夏天",
      subtitleEn: "SUMMER STYLE, LOCAL LEGEND",
      seal: "凉",
    },
    personSlot: { x: 0.5, y: 0.48, scale: 0.7, shape: "full" },
  },
  {
    id: "dragon",
    name: "龙年灯会 / Dragon Festival",
    category: "festival",
    renderer: "dragonFestival",
    colors: ["#7d1712", "#f2c45a", "#111820"],
    copy: { seal: "潮" },
    personSlot: { x: 0.5, y: 0.44, scale: 0.76, shape: "oval" },
  },
  {
    id: "opera",
    name: "京剧舞台 / Opera Stage Pop",
    category: "culture",
    renderer: "operaStage",
    colors: ["#10233b", "#e64a43", "#f3d575"],
    copy: { seal: "京" },
    personSlot: { x: 0.5, y: 0.45, scale: 0.76, shape: "arch" },
  },
  {
    id: "lantern",
    name: "灯笼街 / Lantern Street",
    category: "festival",
    renderer: "lanternStreet",
    colors: ["#14211d", "#d63f35", "#f5bd4d"],
    copy: { seal: "福" },
    personSlot: { x: 0.5, y: 0.44, scale: 0.76, shape: "oval" },
  },
  {
    id: "greatwall",
    name: "长城混搭 / Great Wall Remix",
    category: "landmark",
    renderer: "greatWall",
    colors: ["#183543", "#d04a37", "#e7c466"],
    copy: { seal: "游" },
    personSlot: { x: 0.5, y: 0.44, scale: 0.74, shape: "oval" },
  },
  {
    id: "porcelain",
    name: "青花瓷 / Blue Porcelain",
    category: "culture",
    renderer: "porcelain",
    colors: ["#e9efe9", "#1d5b9a", "#bf2f32"],
    copy: { seal: "青" },
    personSlot: { x: 0.5, y: 0.44, scale: 0.74, shape: "oval" },
  },
  {
    id: "neon",
    name: "赛博唐人街 / Cyber Chinatown",
    category: "scene",
    renderer: "cyberChinatown",
    colors: ["#101421", "#ee3e52", "#37d6c6"],
    copy: { seal: "潮" },
    personSlot: { x: 0.5, y: 0.44, scale: 0.74, shape: "oval" },
  },
];
